INFO 2023-10-17 07:34:21,777 Watching for file changes with StatReloader
ERROR 2023-10-17 07:46:30,032 Internal Server Error: /
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 07:46:30,033 "GET / HTTP/1.1" 500 173258
WARNING 2023-10-17 07:46:31,144 Not Found: /favicon.ico
WARNING 2023-10-17 07:46:31,145 "GET /favicon.ico HTTP/1.1" 404 9359
INFO 2023-10-17 07:50:39,647 Watching for file changes with StatReloader
INFO 2023-10-17 07:50:51,485 "GET / HTTP/1.1" 302 0
INFO 2023-10-17 07:50:52,684 "GET /accounts/login/?next=/ HTTP/1.1" 200 3985
INFO 2023-10-17 07:50:52,762 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 200 6454
INFO 2023-10-17 07:50:52,763 "GET /static/dist/css/login-page.css HTTP/1.1" 200 8610
INFO 2023-10-17 07:50:52,763 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 200 58578
INFO 2023-10-17 07:50:52,763 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 200 19724
INFO 2023-10-17 07:50:52,764 "GET /static/dist/img/login.png HTTP/1.1" 200 144918
INFO 2023-10-17 07:50:52,765 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 200 686707
INFO 2023-10-17 07:50:52,768 "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 200 88145
INFO 2023-10-17 07:50:52,779 "GET /static/dist/js/demo.js HTTP/1.1" 200 12616
INFO 2023-10-17 07:50:52,779 "GET /static/dist/js/jquery.formset.js HTTP/1.1" 200 13632
INFO 2023-10-17 07:50:52,780 "GET /static/dist/js/adminlte.js HTTP/1.1" 200 57530
INFO 2023-10-17 07:50:52,780 "GET /static/plugins/toastr/toastr.min.js HTTP/1.1" 200 5251
INFO 2023-10-17 07:50:52,780 "GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js HTTP/1.1" 200 42383
INFO 2023-10-17 07:50:52,781 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 80698
INFO 2023-10-17 07:50:53,374 "GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 79444
INFO 2023-10-17 07:51:07,920 "POST /users/accounts/login/ HTTP/1.1" 302 0
INFO 2023-10-17 07:51:10,612 "GET / HTTP/1.1" 200 14710
INFO 2023-10-17 07:51:10,689 "GET /static/dist/css/admin-dashboard.css HTTP/1.1" 200 1736
INFO 2023-10-17 07:51:10,694 "GET /static/plugins/Datatables/datatables.min.css HTTP/1.1" 200 25780
WARNING 2023-10-17 07:51:10,696 "GET /static/select2/css/select2.min.css HTTP/1.1" 404 1840
WARNING 2023-10-17 07:51:10,697 "GET /static/select2/js/select2.min.js HTTP/1.1" 404 1834
WARNING 2023-10-17 07:51:12,404 Not Found: /vendor/bootstrap-4.1/popper.min.js
WARNING 2023-10-17 07:51:12,404 "GET /vendor/bootstrap-4.1/popper.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 07:51:14,027 Not Found: /vendor/counter-up/jquery.waypoints.min.js
WARNING 2023-10-17 07:51:14,028 "GET /vendor/counter-up/jquery.waypoints.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 07:51:14,256 Not Found: /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js
WARNING 2023-10-17 07:51:14,257 "GET /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 404 9497
WARNING 2023-10-17 07:51:14,493 Not Found: /vendor/bootstrap-4.1/bootstrap.min.js
WARNING 2023-10-17 07:51:14,494 "GET /vendor/bootstrap-4.1/bootstrap.min.js HTTP/1.1" 404 9437
WARNING 2023-10-17 07:51:14,730 Not Found: /vendor/slick/slick.min.js
WARNING 2023-10-17 07:51:14,731 "GET /vendor/slick/slick.min.js HTTP/1.1" 404 9401
WARNING 2023-10-17 07:51:14,957 Not Found: /vendor/wow/wow.min.js
WARNING 2023-10-17 07:51:14,958 "GET /vendor/wow/wow.min.js HTTP/1.1" 404 9389
WARNING 2023-10-17 07:51:15,211 Not Found: /vendor/animsition/animsition.min.js
WARNING 2023-10-17 07:51:15,212 "GET /vendor/animsition/animsition.min.js HTTP/1.1" 404 9431
WARNING 2023-10-17 07:51:15,515 Not Found: /vendor/counter-up/jquery.counterup.min.js
WARNING 2023-10-17 07:51:15,515 "GET /vendor/counter-up/jquery.counterup.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 07:51:15,742 Not Found: /vendor/circle-progress/circle-progress.min.js
WARNING 2023-10-17 07:51:15,743 "GET /vendor/circle-progress/circle-progress.min.js HTTP/1.1" 404 9461
WARNING 2023-10-17 07:51:15,976 Not Found: /vendor/perfect-scrollbar/perfect-scrollbar.js
WARNING 2023-10-17 07:51:15,977 "GET /vendor/perfect-scrollbar/perfect-scrollbar.js HTTP/1.1" 404 9461
WARNING 2023-10-17 07:51:16,315 Not Found: /vendor/chartjs/Chart.bundle.min.js
WARNING 2023-10-17 07:51:16,319 "GET /vendor/chartjs/Chart.bundle.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 07:51:16,623 Not Found: /vendor/select2/select2.min.js
WARNING 2023-10-17 07:51:16,629 "GET /vendor/select2/select2.min.js HTTP/1.1" 404 9413
INFO 2023-10-17 07:51:16,671 "GET /static/plugins/Datatables/datatables.min.js HTTP/1.1" 200 2042446
INFO 2023-10-17 07:51:16,723 "GET /static/dist/js/admin-dashboard.js HTTP/1.1" 304 0
INFO 2023-10-17 07:51:16,818 "GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13584
WARNING 2023-10-17 07:51:16,866 Not Found: /vendor/vector-map/jquery.vmap.js
WARNING 2023-10-17 07:51:16,866 "GET /vendor/vector-map/jquery.vmap.js HTTP/1.1" 404 9422
WARNING 2023-10-17 07:51:17,100 Not Found: /vendor/vector-map/jquery.vmap.min.js
WARNING 2023-10-17 07:51:17,100 "GET /vendor/vector-map/jquery.vmap.min.js HTTP/1.1" 404 9434
WARNING 2023-10-17 07:51:17,381 Not Found: /vendor/vector-map/jquery.vmap.sampledata.js
WARNING 2023-10-17 07:51:17,382 "GET /vendor/vector-map/jquery.vmap.sampledata.js HTTP/1.1" 404 9455
WARNING 2023-10-17 07:51:17,647 Not Found: /vendor/vector-map/jquery.vmap.world.js
WARNING 2023-10-17 07:51:17,647 "GET /vendor/vector-map/jquery.vmap.world.js HTTP/1.1" 404 9440
WARNING 2023-10-17 07:51:17,954 Not Found: /js/main.js
WARNING 2023-10-17 07:51:17,955 "GET /js/main.js HTTP/1.1" 404 9356
INFO 2023-10-17 08:12:02,024 "GET /users/accounts/logout/ HTTP/1.1" 302 0
INFO 2023-10-17 08:12:02,500 "GET / HTTP/1.1" 302 0
INFO 2023-10-17 08:12:03,724 "GET /accounts/login/?next=/ HTTP/1.1" 200 3985
INFO 2023-10-17 08:33:10,233 "GET /accounts/login/?next=/ HTTP/1.1" 200 3985
INFO 2023-10-17 08:33:18,072 Watching for file changes with StatReloader
INFO 2023-10-17 08:33:35,556 "GET /accounts/login/?next=/ HTTP/1.1" 200 3985
INFO 2023-10-17 08:42:17,204 /home/lanlokun/Desktop/test_portal/apps/corecode/views.py changed, reloading.
INFO 2023-10-17 08:42:17,448 Watching for file changes with StatReloader
INFO 2023-10-17 08:43:12,516 Watching for file changes with StatReloader
INFO 2023-10-17 08:46:04,617 "POST /users/accounts/login/ HTTP/1.1" 302 0
INFO 2023-10-17 08:46:06,992 "GET / HTTP/1.1" 200 14710
WARNING 2023-10-17 08:46:07,057 "GET /static/select2/css/select2.min.css HTTP/1.1" 404 1840
WARNING 2023-10-17 08:46:07,098 "GET /static/select2/js/select2.min.js HTTP/1.1" 404 1834
WARNING 2023-10-17 08:46:10,237 Not Found: /vendor/bootstrap-4.1/popper.min.js
WARNING 2023-10-17 08:46:10,238 "GET /vendor/bootstrap-4.1/popper.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 08:46:12,233 Not Found: /vendor/wow/wow.min.js
WARNING 2023-10-17 08:46:12,233 "GET /vendor/wow/wow.min.js HTTP/1.1" 404 9389
WARNING 2023-10-17 08:46:13,738 Not Found: /vendor/animsition/animsition.min.js
WARNING 2023-10-17 08:46:13,738 "GET /vendor/animsition/animsition.min.js HTTP/1.1" 404 9431
WARNING 2023-10-17 08:46:15,029 Not Found: /vendor/slick/slick.min.js
WARNING 2023-10-17 08:46:15,029 "GET /vendor/slick/slick.min.js HTTP/1.1" 404 9401
WARNING 2023-10-17 08:46:15,287 Not Found: /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js
WARNING 2023-10-17 08:46:15,288 "GET /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 404 9497
WARNING 2023-10-17 08:46:15,527 Not Found: /vendor/bootstrap-4.1/bootstrap.min.js
WARNING 2023-10-17 08:46:15,528 "GET /vendor/bootstrap-4.1/bootstrap.min.js HTTP/1.1" 404 9437
WARNING 2023-10-17 08:46:16,435 Not Found: /vendor/counter-up/jquery.waypoints.min.js
WARNING 2023-10-17 08:46:16,436 "GET /vendor/counter-up/jquery.waypoints.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 08:46:16,811 Not Found: /vendor/counter-up/jquery.counterup.min.js
WARNING 2023-10-17 08:46:16,811 "GET /vendor/counter-up/jquery.counterup.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 08:46:17,049 Not Found: /vendor/circle-progress/circle-progress.min.js
WARNING 2023-10-17 08:46:17,049 "GET /vendor/circle-progress/circle-progress.min.js HTTP/1.1" 404 9461
WARNING 2023-10-17 08:46:17,848 Not Found: /vendor/perfect-scrollbar/perfect-scrollbar.js
WARNING 2023-10-17 08:46:17,849 "GET /vendor/perfect-scrollbar/perfect-scrollbar.js HTTP/1.1" 404 9461
WARNING 2023-10-17 08:46:18,329 Not Found: /vendor/chartjs/Chart.bundle.min.js
WARNING 2023-10-17 08:46:18,330 "GET /vendor/chartjs/Chart.bundle.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 08:46:18,566 Not Found: /vendor/select2/select2.min.js
WARNING 2023-10-17 08:46:18,567 "GET /vendor/select2/select2.min.js HTTP/1.1" 404 9413
WARNING 2023-10-17 08:46:19,243 Not Found: /vendor/vector-map/jquery.vmap.js
WARNING 2023-10-17 08:46:19,243 "GET /vendor/vector-map/jquery.vmap.js HTTP/1.1" 404 9422
WARNING 2023-10-17 08:46:19,850 Not Found: /vendor/vector-map/jquery.vmap.min.js
WARNING 2023-10-17 08:46:19,850 "GET /vendor/vector-map/jquery.vmap.min.js HTTP/1.1" 404 9434
WARNING 2023-10-17 08:46:20,162 Not Found: /vendor/vector-map/jquery.vmap.sampledata.js
WARNING 2023-10-17 08:46:20,164 "GET /vendor/vector-map/jquery.vmap.sampledata.js HTTP/1.1" 404 9455
WARNING 2023-10-17 08:46:20,646 Not Found: /vendor/vector-map/jquery.vmap.world.js
WARNING 2023-10-17 08:46:20,647 "GET /vendor/vector-map/jquery.vmap.world.js HTTP/1.1" 404 9440
WARNING 2023-10-17 08:46:21,460 Not Found: /js/main.js
WARNING 2023-10-17 08:46:21,461 "GET /js/main.js HTTP/1.1" 404 9356
INFO 2023-10-17 08:47:41,903 "GET /student/list HTTP/1.1" 200 15755
WARNING 2023-10-17 08:47:41,928 "GET /static/select2/css/select2.min.css HTTP/1.1" 404 1840
WARNING 2023-10-17 08:47:41,941 "GET /static/select2/js/select2.min.js HTTP/1.1" 404 1834
WARNING 2023-10-17 08:47:43,436 Not Found: /student/vendor/bootstrap-4.1/popper.min.js
WARNING 2023-10-17 08:47:43,436 "GET /student/vendor/bootstrap-4.1/popper.min.js HTTP/1.1" 404 11087
WARNING 2023-10-17 08:47:44,893 Not Found: /student/vendor/counter-up/jquery.waypoints.min.js
WARNING 2023-10-17 08:47:44,893 "GET /student/vendor/counter-up/jquery.waypoints.min.js HTTP/1.1" 404 11108
WARNING 2023-10-17 08:47:46,404 Not Found: /student/vendor/counter-up/jquery.counterup.min.js
WARNING 2023-10-17 08:47:46,405 "GET /student/vendor/counter-up/jquery.counterup.min.js HTTP/1.1" 404 11108
WARNING 2023-10-17 08:47:47,908 Not Found: /student/vendor/circle-progress/circle-progress.min.js
WARNING 2023-10-17 08:47:47,909 "GET /student/vendor/circle-progress/circle-progress.min.js HTTP/1.1" 404 11120
WARNING 2023-10-17 08:47:49,400 Not Found: /student/vendor/perfect-scrollbar/perfect-scrollbar.js
WARNING 2023-10-17 08:47:49,400 "GET /student/vendor/perfect-scrollbar/perfect-scrollbar.js HTTP/1.1" 404 11120
WARNING 2023-10-17 08:47:50,973 Not Found: /student/vendor/chartjs/Chart.bundle.min.js
WARNING 2023-10-17 08:47:50,974 "GET /student/vendor/chartjs/Chart.bundle.min.js HTTP/1.1" 404 11087
WARNING 2023-10-17 08:47:52,553 Not Found: /student/vendor/select2/select2.min.js
WARNING 2023-10-17 08:47:52,553 "GET /student/vendor/select2/select2.min.js HTTP/1.1" 404 11072
WARNING 2023-10-17 08:48:15,709 Not Found: /student/vendor/vector-map/jquery.vmap.js
WARNING 2023-10-17 08:48:15,709 "GET /student/vendor/vector-map/jquery.vmap.js HTTP/1.1" 404 11081
ERROR 2023-10-17 08:48:15,833 Internal Server Error: /student/vendor/slick/slick.min.js
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:15,834 "GET /student/vendor/slick/slick.min.js HTTP/1.1" 500 173524
ERROR 2023-10-17 08:48:15,935 Internal Server Error: /student/vendor/wow/wow.min.js
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:15,935 "GET /student/vendor/wow/wow.min.js HTTP/1.1" 500 173368
ERROR 2023-10-17 08:48:16,014 Internal Server Error: /student/vendor/bootstrap-4.1/bootstrap.min.js
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:16,041 Internal Server Error: /student/vendor/animsition/animsition.min.js
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:16,042 "GET /student/vendor/animsition/animsition.min.js HTTP/1.1" 500 173494
ERROR 2023-10-17 08:48:16,074 Internal Server Error: /student/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:16,075 "GET /student/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 500 173692
ERROR 2023-10-17 08:48:16,238 Internal Server Error: /users/accounts/logout/
Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lanlokun/Desktop/test_portal/apps/corecode/middleware.py", line 11, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lanlokun/Desktop/test_portal/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-ck9f4u9ehpqs73cujl9g-a.oregon-postgres.render.com" to address: Name or service not known

ERROR 2023-10-17 08:48:16,240 "GET /users/accounts/logout/ HTTP/1.1" 500 173712
WARNING 2023-10-17 08:48:17,210 Not Found: /student/vendor/vector-map/jquery.vmap.min.js
WARNING 2023-10-17 08:48:17,420 Not Found: /student/vendor/vector-map/jquery.vmap.world.js
WARNING 2023-10-17 08:48:17,661 Not Found: /student/vendor/vector-map/jquery.vmap.sampledata.js
WARNING 2023-10-17 08:48:17,923 Not Found: /student/js/main.js
INFO 2023-10-17 08:48:40,862 "GET /users/accounts/logout/ HTTP/1.1" 302 0
INFO 2023-10-17 08:48:41,476 "GET / HTTP/1.1" 302 0
INFO 2023-10-17 08:48:42,823 "GET /accounts/login/?next=/ HTTP/1.1" 200 3985
INFO 2023-10-17 08:49:39,638 "POST /users/accounts/login/ HTTP/1.1" 302 0
INFO 2023-10-17 08:49:42,404 "GET / HTTP/1.1" 200 14036
WARNING 2023-10-17 08:49:42,460 "GET /static/select2/css/select2.min.css HTTP/1.1" 404 1840
WARNING 2023-10-17 08:49:42,505 "GET /static/select2/js/select2.min.js HTTP/1.1" 404 1834
WARNING 2023-10-17 08:49:45,807 Not Found: /vendor/slick/slick.min.js
WARNING 2023-10-17 08:49:45,808 "GET /vendor/slick/slick.min.js HTTP/1.1" 404 9401
WARNING 2023-10-17 08:49:46,056 Not Found: /vendor/bootstrap-4.1/popper.min.js
WARNING 2023-10-17 08:49:46,056 "GET /vendor/bootstrap-4.1/popper.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 08:49:46,285 Not Found: /vendor/bootstrap-4.1/bootstrap.min.js
WARNING 2023-10-17 08:49:46,285 "GET /vendor/bootstrap-4.1/bootstrap.min.js HTTP/1.1" 404 9437
WARNING 2023-10-17 08:49:47,554 Not Found: /vendor/wow/wow.min.js
WARNING 2023-10-17 08:49:47,554 "GET /vendor/wow/wow.min.js HTTP/1.1" 404 9389
WARNING 2023-10-17 08:49:47,786 Not Found: /vendor/animsition/animsition.min.js
WARNING 2023-10-17 08:49:47,786 "GET /vendor/animsition/animsition.min.js HTTP/1.1" 404 9431
WARNING 2023-10-17 08:49:48,021 Not Found: /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js
WARNING 2023-10-17 08:49:48,022 "GET /vendor/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 404 9497
WARNING 2023-10-17 08:49:49,050 Not Found: /vendor/counter-up/jquery.waypoints.min.js
WARNING 2023-10-17 08:49:49,050 "GET /vendor/counter-up/jquery.waypoints.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 08:49:49,285 Not Found: /vendor/counter-up/jquery.counterup.min.js
WARNING 2023-10-17 08:49:49,285 "GET /vendor/counter-up/jquery.counterup.min.js HTTP/1.1" 404 9449
WARNING 2023-10-17 08:49:49,530 Not Found: /vendor/circle-progress/circle-progress.min.js
WARNING 2023-10-17 08:49:49,530 "GET /vendor/circle-progress/circle-progress.min.js HTTP/1.1" 404 9461
WARNING 2023-10-17 08:49:50,556 Not Found: /vendor/perfect-scrollbar/perfect-scrollbar.js
WARNING 2023-10-17 08:49:50,557 "GET /vendor/perfect-scrollbar/perfect-scrollbar.js HTTP/1.1" 404 9461
WARNING 2023-10-17 08:49:50,797 Not Found: /vendor/chartjs/Chart.bundle.min.js
WARNING 2023-10-17 08:49:50,798 "GET /vendor/chartjs/Chart.bundle.min.js HTTP/1.1" 404 9428
WARNING 2023-10-17 08:49:51,031 Not Found: /vendor/select2/select2.min.js
WARNING 2023-10-17 08:49:51,031 "GET /vendor/select2/select2.min.js HTTP/1.1" 404 9413
WARNING 2023-10-17 08:49:52,251 Not Found: /vendor/vector-map/jquery.vmap.js
WARNING 2023-10-17 08:49:52,252 "GET /vendor/vector-map/jquery.vmap.js HTTP/1.1" 404 9422
WARNING 2023-10-17 08:49:52,482 Not Found: /vendor/vector-map/jquery.vmap.min.js
WARNING 2023-10-17 08:49:52,482 "GET /vendor/vector-map/jquery.vmap.min.js HTTP/1.1" 404 9434
WARNING 2023-10-17 08:49:52,713 Not Found: /vendor/vector-map/jquery.vmap.sampledata.js
WARNING 2023-10-17 08:49:52,713 "GET /vendor/vector-map/jquery.vmap.sampledata.js HTTP/1.1" 404 9455
WARNING 2023-10-17 08:49:53,777 Not Found: /vendor/vector-map/jquery.vmap.world.js
WARNING 2023-10-17 08:49:53,777 "GET /vendor/vector-map/jquery.vmap.world.js HTTP/1.1" 404 9440
WARNING 2023-10-17 08:49:54,017 Not Found: /js/main.js
WARNING 2023-10-17 08:49:54,017 "GET /js/main.js HTTP/1.1" 404 9356
INFO 2023-10-17 08:57:02,517 /home/lanlokun/Desktop/test_portal/apps/corecode/views.py changed, reloading.
INFO 2023-10-17 08:57:02,749 Watching for file changes with StatReloader
INFO 2023-10-17 09:07:40,734 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 09:08:41,503 Watching for file changes with StatReloader
INFO 2023-10-17 09:09:27,140 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 09:09:27,379 Watching for file changes with StatReloader
INFO 2023-10-17 09:09:55,625 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 09:09:55,847 Watching for file changes with StatReloader
INFO 2023-10-17 09:19:14,228 /home/lanlokun/Desktop/test_portal/apps/corecode/views.py changed, reloading.
INFO 2023-10-17 09:19:14,474 Watching for file changes with StatReloader
INFO 2023-10-17 09:19:35,744 /home/lanlokun/Desktop/test_portal/apps/corecode/urls.py changed, reloading.
INFO 2023-10-17 09:19:35,963 Watching for file changes with StatReloader
INFO 2023-10-17 09:30:37,715 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 11:23:38,955 Watching for file changes with StatReloader
INFO 2023-10-17 11:36:26,681 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 11:36:27,017 Watching for file changes with StatReloader
INFO 2023-10-17 11:36:47,961 Watching for file changes with StatReloader
INFO 2023-10-17 11:37:25,375 /home/lanlokun/Desktop/test_portal/school_app/settings.py changed, reloading.
INFO 2023-10-17 11:37:25,655 Watching for file changes with StatReloader
